/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImportFigmaRouteImport } from './routes/api/import-figma'
import { Route as ApiImportCodeRouteImport } from './routes/api/import-code'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiCloneSplatRouteImport } from './routes/api/clone.$'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportFigmaRoute = ApiImportFigmaRouteImport.update({
  id: '/api/import-figma',
  path: '/api/import-figma',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportCodeRoute = ApiImportCodeRouteImport.update({
  id: '/api/import-code',
  path: '/api/import-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloneSplatRoute = ApiCloneSplatRouteImport.update({
  id: '/api/clone/$',
  path: '/api/clone/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/import-code': typeof ApiImportCodeRoute
  '/api/import-figma': typeof ApiImportFigmaRoute
  '/api/clone/$': typeof ApiCloneSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/import-code': typeof ApiImportCodeRoute
  '/api/import-figma': typeof ApiImportFigmaRoute
  '/api/clone/$': typeof ApiCloneSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/import-code': typeof ApiImportCodeRoute
  '/api/import-figma': typeof ApiImportFigmaRoute
  '/api/clone/$': typeof ApiCloneSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/api/generate'
    | '/api/import-code'
    | '/api/import-figma'
    | '/api/clone/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace'
    | '/api/generate'
    | '/api/import-code'
    | '/api/import-figma'
    | '/api/clone/$'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/api/generate'
    | '/api/import-code'
    | '/api/import-figma'
    | '/api/clone/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiImportCodeRoute: typeof ApiImportCodeRoute
  ApiImportFigmaRoute: typeof ApiImportFigmaRoute
  ApiCloneSplatRoute: typeof ApiCloneSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-figma': {
      id: '/api/import-figma'
      path: '/api/import-figma'
      fullPath: '/api/import-figma'
      preLoaderRoute: typeof ApiImportFigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-code': {
      id: '/api/import-code'
      path: '/api/import-code'
      fullPath: '/api/import-code'
      preLoaderRoute: typeof ApiImportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clone/$': {
      id: '/api/clone/$'
      path: '/api/clone/$'
      fullPath: '/api/clone/$'
      preLoaderRoute: typeof ApiCloneSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiImportCodeRoute: ApiImportCodeRoute,
  ApiImportFigmaRoute: ApiImportFigmaRoute,
  ApiCloneSplatRoute: ApiCloneSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
