import { ROUNDTRIP_MANIFEST_PATH, createRoundtripManifest } from "@/lib/roundtrip-manifest";
import { sharedStyles, type ProjectExportFile } from "@/lib/project-export";
import { prettyCss, prettyTsx } from "@/lib/format-export";
import type { Project } from "@/lib/screen-schema";
import { projectToIr } from "../../core/project-bridge";
import { irChildrenToJsx } from "./jsx";

/**
 * Canvas → real React code (via IR). Two shapes:
 *  - buildReactTsx: a single .tsx file, one component per screen with real
 *    JSX elements (replaces the old dangerouslySetInnerHTML tsxWrap).
 *  - buildReactProjectExport: a runnable Vite+React project ZIP.
 *
 * A marker comment carries screen metadata so re-import restores every screen
 * with its identity — and each component's rendered output is DOM-equal to
 * its canvas screen (unit-tested with renderToStaticMarkup).
 */

export const REACT_EXPORT_MARKER = "sleek.design react export v1";

export type ReactExportMeta = {
  name: string;
  artifactType: "app" | "website" | "figma";
  frame: { w: number; h?: number };
  screens: { id: string; name: string; role: string; export: string }[];
};

function pascalCase(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9]+/g, " ").trim();
  const pascal = cleaned
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  return /^[A-Za-z]/.test(pascal) ? pascal : `Screen${pascal}`;
}

function uniqueExportNames(project: Project): string[] {
  const used = new Set<string>();
  return project.screens.map((screen, i) => {
    let base = `${pascalCase(screen.name || screen.role || `Screen${i + 1}`)}Screen`;
    if (base === "Screen") base = `Screen${i + 1}`;
    let name = base;
    let n = 2;
    while (used.has(name)) name = `${base}${n++}`;
    used.add(name);
    return name;
  });
}

type BuiltScreens = {
  meta: ReactExportMeta;
  /** One `export function <Name>Screen() { … }` block per screen. */
  components: string[];
  hoistedCss: string;
};

async function buildScreenComponents(project: Project): Promise<BuiltScreens> {
  const ir = await projectToIr(project);
  const exportNames = uniqueExportNames(project);
  const hoisted: string[] = [];
  const components: string[] = [];

  for (let i = 0; i < ir.screens.length; i++) {
    const screen = ir.screens[i];
    const { jsx, hoistedCss } = await irChildrenToJsx(screen.nodes, "      ");
    if (hoistedCss) hoisted.push(hoistedCss);
    const elementNodes = screen.nodes.filter((n) => (n as { kind: string }).kind === "element");
    const needsFragment = elementNodes.length !== 1 || screen.nodes.length !== elementNodes.length;
    const body = needsFragment ? `    <>\n${jsx}\n    </>` : jsx.replace(/^ {2}/gm, "");
    components.push(
      `/** ${screen.name} (${screen.role}) */\nexport function ${exportNames[i]}() {\n  return (\n${body}\n  );\n}`,
    );
  }

  return {
    meta: {
      name: ir.meta.name,
      artifactType: ir.meta.artifactType,
      frame: ir.meta.frame,
      screens: ir.screens.map((s, i) => ({
        id: s.id,
        name: s.name,
        role: s.role,
        export: exportNames[i],
      })),
    },
    components,
    hoistedCss: hoisted.join("\n"),
  };
}

function markerComment(meta: ReactExportMeta): string {
  return `// ${REACT_EXPORT_MARKER} ${JSON.stringify(meta)}`;
}

function cssConst(name: string, css: string): string {
  const escaped = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  return `export const ${name} = \`\n${escaped}\`;`;
}

/** Single-file TSX export: all screens as real-JSX components + an App switcher. */
export async function buildReactTsx(project: Project): Promise<string> {
  const { meta, components, hoistedCss } = await buildScreenComponents(project);
  const allCss = [project.designSystemCss, hoistedCss].filter(Boolean).join("\n");

  const app = `export default function App() {
  const screens = [${meta.screens
    .map(
      (s) =>
        `{ id: ${JSON.stringify(s.id)}, name: ${JSON.stringify(s.name)}, Component: ${s.export} }`,
    )
    .join(", ")}] as const;
  const [active, setActive] = React.useState(0);
  const Active = screens[active].Component;
  return (
    <div>
      <style>{DESIGN_SYSTEM_CSS}</style>
      {screens.length > 1 && (
        <nav style={{ display: "flex", gap: "8px", padding: "12px", justifyContent: "center" }}>
          {screens.map((s, i) => (
            <button key={s.id} onClick={() => setActive(i)} style={{ fontWeight: i === active ? 700 : 400 }}>
              {s.name}
            </button>
          ))}
        </nav>
      )}
      <Active />
    </div>
  );
}`;

  const file = [
    markerComment(meta),
    `// Generated by sleek.design — real JSX per screen; re-import this file to restore all screens.`,
    `import * as React from "react";`,
    "",
    cssConst("DESIGN_SYSTEM_CSS", allCss),
    "",
    components.join("\n\n"),
    "",
    app,
    "",
  ].join("\n");

  return prettyTsx(file);
}

/** Full Vite + React project ZIP with one file per screen. */
export async function buildReactProjectExport(project: Project): Promise<ProjectExportFile[]> {
  const { meta, components, hoistedCss } = await buildScreenComponents(project);
  const styles = await sharedStyles(project);
  const title = project.name.replace(/[<>]/g, "").trim() || "Design Export";
  const pkgName = `${
    project.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "design-export"
  }-react`.slice(0, 214);

  const screenFiles = await Promise.all(
    meta.screens.map(async (screen, i) => ({
      path: `src/screens/${screen.export}.tsx`,
      content: await prettyTsx(
        `${components[i].replace(/^\/\*\*/, "/**\n *")}\n`.replace(
          "export function",
          "export default function",
        ),
      ),
    })),
  );

  const appTsx = `${markerComment(meta)}
import { useState } from "react";
${meta.screens.map((s) => `import ${s.export} from "./screens/${s.export}";`).join("\n")}

const SCREENS = [
${meta.screens.map((s) => `  { id: ${JSON.stringify(s.id)}, name: ${JSON.stringify(s.name)}, Component: ${s.export} },`).join("\n")}
] as const;

export default function App() {
  const [activeId, setActiveId] = useState(SCREENS[0]?.id ?? "");
  const active = SCREENS.find((s) => s.id === activeId) ?? SCREENS[0];
  return (
    <main className="export-workspace">
      {SCREENS.length > 1 && (
        <nav className="export-toolbar" aria-label="Screens">
          {SCREENS.map((s) => (
            <button
              key={s.id}
              type="button"
              className={"export-tab" + (s.id === activeId ? " active" : "")}
              onClick={() => setActiveId(s.id)}
            >
              {s.name}
            </button>
          ))}
        </nav>
      )}
      {active && (
        <section className="export-stage">
          <article className="export-screen-shell">
            <h1 className="export-screen-title">{active.name}</h1>
            <div className="mobile-screen">
              <active.Component />
            </div>
          </article>
        </section>
      )}
    </main>
  );
}
`;

  const json = (v: unknown) => JSON.stringify(v, null, 2);

  return [
    {
      path: ROUNDTRIP_MANIFEST_PATH,
      content: `${json(createRoundtripManifest(project, "react"))}\n`,
    },
    {
      path: "package.json",
      content: `${json({
        name: pkgName,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          dev: "vite --host 0.0.0.0",
          build: "tsc -b && vite build",
          preview: "vite preview",
        },
        dependencies: { react: "^19.1.0", "react-dom": "^19.1.0" },
        devDependencies: {
          "@types/react": "^19.1.8",
          "@types/react-dom": "^19.1.6",
          "@vitejs/plugin-react": "^4.6.0",
          typescript: "~5.8.3",
          vite: "^6.3.6",
        },
      })}\n`,
    },
    {
      path: "index.html",
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${title}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
    },
    {
      path: "src/main.tsx",
      content: `import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./styles.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`,
    },
    { path: "src/App.tsx", content: await prettyTsx(appTsx) },
    ...screenFiles,
    {
      path: "src/styles.css",
      content: await prettyCss([styles, hoistedCss].filter(Boolean).join("\n")),
    },
    {
      path: "tsconfig.json",
      content: `${json({
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          isolatedModules: true,
          moduleDetection: "force",
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
        },
        include: ["src"],
      })}\n`,
    },
    {
      path: "vite.config.ts",
      content: `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`,
    },
    {
      path: "README.md",
      content: `# ${title}\n\nReact export generated by sleek.design — every screen is a real JSX component.\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
    },
  ];
}
