import { prettyCss, prettyHtml } from "@/lib/format-export";
import { ROUNDTRIP_MANIFEST_PATH, createRoundtripManifest } from "@/lib/roundtrip-manifest";
import type { Project } from "@/lib/screen-schema";

export type ProjectExportFile = {
  path: string;
  content: string;
};

type ExportedScreen = {
  id: string;
  name: string;
  role: string;
  html: string;
};

function packageName(project: Project, suffix: string): string {
  const base = project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "design-export";
  return `${base}-${suffix}`.slice(0, 214);
}

function appTitle(project: Project): string {
  return project.name.replace(/[<>]/g, "").trim() || "Design Export";
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function frameWidth(project: Project): number | null {
  const width = (project as any)?.format_config?.frame?.width;
  return typeof width === "number" && Number.isFinite(width) ? width : null;
}

function isWebsite(project: Project): boolean {
  return (project as any)?.format_config?.artifactType === "website";
}

async function exportedScreens(project: Project): Promise<ExportedScreen[]> {
  return Promise.all(
    project.screens.map(async (screen) => ({
      id: screen.id,
      name: screen.name,
      role: screen.role,
      html: (await prettyHtml(screen.html)).trim(),
    })),
  );
}

async function sharedStyles(project: Project): Promise<string> {
  const css = await prettyCss(project.designSystemCss);
  const width = frameWidth(project);
  const shellWidth = isWebsite(project) ? `${width ?? 1536}px` : `${width ?? 375}px`;

  return [
    "/* Generated by sleek.design. Shared design-system styles are kept global so imported HTML renders unchanged. */",
    css.trim(),
    "",
    ":root {",
    "  color-scheme: light;",
    "  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
    "  background: #f4f5f7;",
    "  color: #111827;",
    "}",
    "",
    "* {",
    "  box-sizing: border-box;",
    "}",
    "",
    "body {",
    "  margin: 0;",
    "  min-width: 320px;",
    "  min-height: 100vh;",
    "}",
    "",
    "button {",
    "  font: inherit;",
    "}",
    "",
    ".export-workspace {",
    "  min-height: 100vh;",
    "  padding: 32px;",
    "  background:",
    "    radial-gradient(circle at top left, rgba(99, 102, 241, 0.14), transparent 32rem),",
    "    #f4f5f7;",
    "}",
    "",
    ".export-toolbar {",
    "  display: flex;",
    "  flex-wrap: wrap;",
    "  gap: 10px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  margin: 0 auto 24px;",
    "}",
    "",
    ".export-tab {",
    "  border: 1px solid rgba(17, 24, 39, 0.12);",
    "  border-radius: 999px;",
    "  padding: 8px 14px;",
    "  color: #4b5563;",
    "  background: rgba(255, 255, 255, 0.76);",
    "  cursor: pointer;",
    "  transition: all 150ms ease;",
    "}",
    "",
    ".export-tab:hover,",
    ".export-tab.active {",
    "  color: #111827;",
    "  border-color: rgba(17, 24, 39, 0.26);",
    "  background: #ffffff;",
    "  box-shadow: 0 8px 28px rgba(15, 23, 42, 0.10);",
    "}",
    "",
    ".export-stage {",
    "  display: flex;",
    "  justify-content: center;",
    "  min-width: 0;",
    "}",
    "",
    ".export-screen-shell {",
    `  width: min(100%, ${shellWidth});`,
    "}",
    "",
    ".export-screen-title {",
    "  margin: 0 0 12px;",
    "  color: #374151;",
    "  font-size: 13px;",
    "  font-weight: 700;",
    "  letter-spacing: 0.08em;",
    "  text-transform: uppercase;",
    "}",
    "",
    ".mobile-screen {",
    "  width: 100%;",
    "  overflow: hidden;",
    "  border-radius: 28px;",
    "  background: #fff;",
    "  box-shadow: 0 24px 70px rgba(15, 23, 42, 0.18);",
    "}",
    "",
    isWebsite(project)
      ? [
          ".mobile-screen {",
          "  border-radius: 18px;",
          "}",
        ].join("\n")
      : [
          ".mobile-screen {",
          "  max-width: 430px;",
          "  margin: 0 auto;",
          "}",
        ].join("\n"),
    "",
    "@media (max-width: 720px) {",
    "  .export-workspace {",
    "    padding: 18px;",
    "  }",
    "",
    "  .mobile-screen {",
    "    border-radius: 22px;",
    "  }",
    "}",
    "",
  ].join("\n");
}

export async function buildVueProjectExport(project: Project): Promise<ProjectExportFile[]> {
  const title = appTitle(project);
  const screens = await exportedScreens(project);
  const styles = await sharedStyles(project);
  const pkg = packageName(project, "vue");

  return [
    {
      path: ROUNDTRIP_MANIFEST_PATH,
      content: `${json(createRoundtripManifest(project, "vue"))}\n`,
    },
    {
      path: "package.json",
      content: `${json({
        name: pkg,
        version: "1.0.0",
        private: true,
        type: "module",
        scripts: {
          dev: "vite --host 0.0.0.0",
          build: "vue-tsc -b && vite build",
          preview: "vite preview",
        },
        dependencies: {
          vue: "^3.5.18",
        },
        devDependencies: {
          "@vitejs/plugin-vue": "^5.2.4",
          typescript: "~5.8.3",
          vite: "^6.3.6",
          "vue-tsc": "^2.2.12",
        },
      })}\n`,
    },
    {
      path: "index.html",
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${title}</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/src/main.ts"></script>\n  </body>\n</html>\n`,
    },
    {
      path: "src/main.ts",
      content: `import { createApp } from "vue";\nimport App from "./App.vue";\nimport "./styles.css";\n\ncreateApp(App).mount("#app");\n`,
    },
    {
      path: "src/App.vue",
      content: `<script setup lang="ts">\nimport { computed, ref } from "vue";\n\ntype ExportedScreen = {\n  id: string;\n  name: string;\n  role: string;\n  html: string;\n};\n\nconst screens: ExportedScreen[] = ${json(screens)};\n\nconst activeScreenId = ref(screens[0]?.id ?? "");\nconst activeScreen = computed(() => screens.find((screen) => screen.id === activeScreenId.value) ?? screens[0]);\n</script>\n\n<template>\n  <main class="export-workspace">\n    <nav v-if="screens.length > 1" class="export-toolbar" aria-label="Screens">\n      <button\n        v-for="screen in screens"\n        :key="screen.id"\n        type="button"\n        class="export-tab"\n        :class="{ active: screen.id === activeScreenId }"\n        @click="activeScreenId = screen.id"\n      >\n        {{ screen.name }}\n      </button>\n    </nav>\n\n    <section v-if="activeScreen" class="export-stage">\n      <article class="export-screen-shell">\n        <h1 class="export-screen-title">{{ activeScreen.name }}</h1>\n        <div class="mobile-screen">\n          <div v-html="activeScreen.html"></div>\n        </div>\n      </article>\n    </section>\n  </main>\n</template>\n`,
    },
    {
      path: "src/styles.css",
      content: styles,
    },
    {
      path: "tsconfig.json",
      content: `${json({
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          module: "ESNext",
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          isolatedModules: true,
          moduleDetection: "force",
          noEmit: true,
          jsx: "preserve",
          strict: true,
        },
        include: ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
      })}\n`,
    },
    {
      path: "vite.config.ts",
      content: `import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\n\nexport default defineConfig({\n  plugins: [vue()],\n});\n`,
    },
    {
      path: "README.md",
      content: `# ${title}\n\nVue export generated by sleek.design.\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Production build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
    },
  ];
}

export async function buildAngularProjectExport(project: Project): Promise<ProjectExportFile[]> {
  const title = appTitle(project);
  const screens = await exportedScreens(project);
  const styles = await sharedStyles(project);
  const pkg = packageName(project, "angular");

  return [
    {
      path: ROUNDTRIP_MANIFEST_PATH,
      content: `${json(createRoundtripManifest(project, "angular"))}\n`,
    },
    {
      path: "package.json",
      content: `${json({
        name: pkg,
        version: "1.0.0",
        private: true,
        scripts: {
          ng: "ng",
          start: "ng serve --host 0.0.0.0",
          build: "ng build",
          watch: "ng build --watch --configuration development",
        },
        dependencies: {
          "@angular/animations": "^19.2.14",
          "@angular/common": "^19.2.14",
          "@angular/compiler": "^19.2.14",
          "@angular/core": "^19.2.14",
          "@angular/forms": "^19.2.14",
          "@angular/platform-browser": "^19.2.14",
          "@angular/router": "^19.2.14",
          rxjs: "~7.8.2",
          tslib: "^2.8.1",
          "zone.js": "~0.15.1",
        },
        devDependencies: {
          "@angular-devkit/build-angular": "^19.2.15",
          "@angular/cli": "^19.2.15",
          "@angular/compiler-cli": "^19.2.14",
          typescript: "~5.8.3",
        },
      })}\n`,
    },
    {
      path: "angular.json",
      content: `${json({
        version: 1,
        newProjectRoot: "projects",
        projects: {
          app: {
            projectType: "application",
            schematics: {},
            root: "",
            sourceRoot: "src",
            prefix: "app",
            architect: {
              build: {
                builder: "@angular-devkit/build-angular:application",
                options: {
                  outputPath: "dist/app",
                  index: "src/index.html",
                  browser: "src/main.ts",
                  polyfills: ["zone.js"],
                  tsConfig: "tsconfig.app.json",
                  assets: ["src/favicon.ico", "src/assets"],
                  styles: ["src/styles.css"],
                  scripts: [],
                },
                configurations: {
                  production: {
                    budgets: [
                      { type: "initial", maximumWarning: "1mb", maximumError: "2mb" },
                      { type: "anyComponentStyle", maximumWarning: "12kb", maximumError: "24kb" },
                    ],
                    outputHashing: "all",
                  },
                  development: {
                    optimization: false,
                    extractLicenses: false,
                    sourceMap: true,
                  },
                },
                defaultConfiguration: "production",
              },
              serve: {
                builder: "@angular-devkit/build-angular:dev-server",
                configurations: {
                  production: { buildTarget: "app:build:production" },
                  development: { buildTarget: "app:build:development" },
                },
                defaultConfiguration: "development",
              },
            },
          },
        },
      })}\n`,
    },
    {
      path: "src/index.html",
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <title>${title}</title>\n    <base href="/" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n  </head>\n  <body>\n    <app-root></app-root>\n  </body>\n</html>\n`,
    },
    {
      path: "src/main.ts",
      content: `import { bootstrapApplication } from "@angular/platform-browser";\nimport { AppComponent } from "./app/app.component";\n\nbootstrapApplication(AppComponent).catch((err) => console.error(err));\n`,
    },
    {
      path: "src/app/app.component.ts",
      content: `import { CommonModule } from "@angular/common";\nimport { Component } from "@angular/core";\nimport { DomSanitizer, SafeHtml } from "@angular/platform-browser";\n\ntype ExportedScreen = {\n  id: string;\n  name: string;\n  role: string;\n  html: string;\n};\n\n@Component({\n  selector: "app-root",\n  standalone: true,\n  imports: [CommonModule],\n  templateUrl: "./app.component.html",\n  styleUrl: "./app.component.css",\n})\nexport class AppComponent {\n  readonly screens: ExportedScreen[] = ${json(screens)};\n  activeScreenId = this.screens[0]?.id ?? "";\n\n  constructor(private readonly sanitizer: DomSanitizer) {}\n\n  get activeScreen(): ExportedScreen | undefined {\n    return this.screens.find((screen) => screen.id === this.activeScreenId) ?? this.screens[0];\n  }\n\n  trustedHtml(html: string): SafeHtml {\n    return this.sanitizer.bypassSecurityTrustHtml(html);\n  }\n}\n`,
    },
    {
      path: "src/app/app.component.html",
      content: `<main class="export-workspace">\n  <nav *ngIf="screens.length > 1" class="export-toolbar" aria-label="Screens">\n    <button\n      *ngFor="let screen of screens"\n      type="button"\n      class="export-tab"\n      [class.active]="screen.id === activeScreenId"\n      (click)="activeScreenId = screen.id"\n    >\n      {{ screen.name }}\n    </button>\n  </nav>\n\n  <section *ngIf="activeScreen as screen" class="export-stage">\n    <article class="export-screen-shell">\n      <h1 class="export-screen-title">{{ screen.name }}</h1>\n      <div class="mobile-screen">\n        <div [innerHTML]="trustedHtml(screen.html)"></div>\n      </div>\n    </article>\n  </section>\n</main>\n`,
    },
    {
      path: "src/app/app.component.css",
      content: ":host { display: block; }\n",
    },
    {
      path: "src/styles.css",
      content: styles,
    },
    {
      path: "src/favicon.ico",
      content: "",
    },
    {
      path: "src/assets/.gitkeep",
      content: "",
    },
    {
      path: "tsconfig.json",
      content: `${json({
        compileOnSave: false,
        compilerOptions: {
          outDir: "./dist/out-tsc",
          strict: true,
          noImplicitOverride: true,
          noPropertyAccessFromIndexSignature: true,
          noImplicitReturns: true,
          noFallthroughCasesInSwitch: true,
          skipLibCheck: true,
          isolatedModules: true,
          esModuleInterop: true,
          sourceMap: true,
          declaration: false,
          experimentalDecorators: true,
          moduleResolution: "bundler",
          importHelpers: true,
          target: "ES2022",
          module: "ES2022",
          lib: ["ES2022", "dom"],
        },
        angularCompilerOptions: {
          enableI18nLegacyMessageIdFormat: false,
          strictInjectionParameters: true,
          strictInputAccessModifiers: true,
          strictTemplates: true,
        },
      })}\n`,
    },
    {
      path: "tsconfig.app.json",
      content: `${json({
        extends: "./tsconfig.json",
        compilerOptions: {
          outDir: "./out-tsc/app",
          types: [],
        },
        files: ["src/main.ts"],
        include: ["src/**/*.d.ts"],
      })}\n`,
    },
    {
      path: "README.md",
      content: `# ${title}\n\nAngular export generated by sleek.design.\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n\n## Production build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`,
    },
  ];
}

export async function createProjectZip(files: ProjectExportFile[]): Promise<Blob> {
  if (typeof window === "undefined") {
    throw new Error("Project ZIP export is only available in the browser.");
  }

  // Keep JSZip out of the route's eager bundle; it is only needed when a user
  // explicitly downloads a framework project.
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  return zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
}
