import { prettyCss, prettyHtml } from "@/lib/format-export";
import { ROUNDTRIP_MANIFEST_PATH, createRoundtripManifest } from "@/lib/roundtrip-manifest";
import type { Project } from "@/lib/screen-schema";

export type ProjectExportFile = {
  path: string;
  content: string;
};

type ExportedScreen = {
  id: string;
  name: string;
  role: string;
  html: string;
};

function packageName(project: Project, suffix: string): string {
  const base = project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "design-export";
  return `${base}-${suffix}`.slice(0, 214);
}

function appTitle(project: Project): string {
  return project.name.replace(/[<>]/g, "").trim() || "Design Export";
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function frameWidth(project: Project): number | null {
  const width = (project as any)?.format_config?.frame?.width;
  return typeof width === "number" && Number.isFinite(width) ? width : null;
}

function isWebsite(project: Project): boolean {
  return (project as any)?.format_config?.artifactType === "website";
}

async function exportedScreens(project: Project): Promise<ExportedScreen[]> {
  return Promise.all(
    project.screens.map(async (screen) => ({
      id: screen.id,
      name: screen.name,
      role: screen.role,
      html: (await prettyHtml(screen.html)).trim(),
    })),
  );
}

export async function sharedStyles(project: Project): Promise<string> {
  const css = await prettyCss(project.designSystemCss);
  const width = frameWidth(project);
  const shellWidth = isWebsite(project) ? `${width ?? 1536}px` : `${width ?? 375}px`;

  return [
    "/* Generated by sleek.design. Shared design-system styles are kept global so imported HTML renders unchanged. */",
    css.trim(),
    "",
    ":root {",
    "  color-scheme: light;",
    "  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
    "  background: #f4f5f7;",
    "  color: #111827;",
    "}",
    "",
    "* {",
    "  box-sizing: border-box;",
    "}",
    "",
    "body {",
    "  margin: 0;",
    "  min-width: 320px;",
    "  min-height: 100vh;",
    "}",
    "",
    "button {",
    "  font: inherit;",
    "}",
    "",
    ".export-workspace {",
    "  min-height: 100vh;",
    "  padding: 32px;",
    "  background:",
    "    radial-gradient(circle at top left, rgba(99, 102, 241, 0.14), transparent 32rem),",
    "    #f4f5f7;",
    "}",
    "",
    ".export-toolbar {",
    "  display: flex;",
    "  flex-wrap: wrap;",
    "  gap: 10px;",
    "  align-items: center;",
    "  justify-content: center;",
    "  margin: 0 auto 24px;",
    "}",
    "",
    ".export-tab {",
    "  border: 1px solid rgba(17, 24, 39, 0.12);",
    "  border-radius: 999px;",
    "  padding: 8px 14px;",
    "  color: #4b5563;",
    "  background: rgba(255, 255, 255, 0.76);",
    "  cursor: pointer;",
    "  transition: all 150ms ease;",
    "}",
    "",
    ".export-tab:hover,",
    ".export-tab.active {",
    "  color: #111827;",
    "  border-color: rgba(17, 24, 39, 0.26);",
    "  background: #ffffff;",
    "  box-shadow: 0 8px 28px rgba(15, 23, 42, 0.10);",
    "}",
    "",
    ".export-stage {",
    "  display: flex;",
    "  justify-content: center;",
    "  min-width: 0;",
    "}",
    "",
    ".export-screen-shell {",
    `  width: min(100%, ${shellWidth});`,
    "}",
    "",
    ".export-screen-title {",
    "  margin: 0 0 12px;",
    "  color: #374151;",
    "  font-size: 13px;",
    "  font-weight: 700;",
    "  letter-spacing: 0.08em;",
    "  text-transform: uppercase;",
    "}",
    "",
    ".mobile-screen {",
    "  width: 100%;",
    "  overflow: hidden;",
    "  border-radius: 28px;",
    "  background: #fff;",
    "  box-shadow: 0 24px 70px rgba(15, 23, 42, 0.18);",
    "}",
    "",
    isWebsite(project)
      ? [
          ".mobile-screen {",
          "  border-radius: 18px;",
          "}",
        ].join("\n")
      : [
          ".mobile-screen {",
          "  max-width: 430px;",
          "  margin: 0 auto;",
          "}",
        ].join("\n"),
    "",
    "@media (max-width: 720px) {",
    "  .export-workspace {",
    "    padding: 18px;",
    "  }",
    "",
    "  .mobile-screen {",
    "    border-radius: 22px;",
    "  }",
    "}",
    "",
  ].join("\n");
}



export async function createProjectZip(files: ProjectExportFile[]): Promise<Blob> {
  if (typeof window === "undefined") {
    throw new Error("Project ZIP export is only available in the browser.");
  }

  // Keep JSZip out of the route's eager bundle; it is only needed when a user
  // explicitly downloads a framework project.
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  for (const file of files) {
    zip.file(file.path, file.content);
  }
  return zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
}
